spring.jooq.sql-dialect=Postgres

# spring.datasource.driver=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/sona
# spring.datasource.username=postgres
# spring.datasource.password=12345
# spring.datasource.hikari.pool-name=MainHikariPool